version: '3.4'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres
  
  distributedcache:
    image: redis
    # build:
    #   context:  .
    #   dockerfile: Dockerfile.redis
    #   args:
    #     - REGISTRY_MIRROR=https://hub-mirror.c.163.com

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
    
